name: Deploy To GitHub Pages

on:
  workflow_dispatch:

permissions: 
  pages: write

jobs: 
  deploy: 
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Deploy to github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
        

